### ISSUE TITLE
Automatic Backup and Restore in case the server crashes

### ISSUE THREAD

**Issue by mattysweeps** [nmtminecraft/SpongeSurvivalGames#12]
It would be a good idea to keep regular backups of the matches while they were going. Say, every five minutes, each RUNNING game would back to a temp file:
- The config
- The players, with inventories and positions
- State
- Other things

So a game could be restored if needed. Of course, the world might be a little different, but this would be better than having to completely restart a match.

**Comment by smarti02** [comment]
agreed

**Comment by smarti02** [comment]
Would that cause lag though?

**Comment by mattysweeps** [comment]
It shouldn't. All config stuff is already in memory. Player information is not that big when you think about it. And we could have an asynchronous thread perform the file saving (after the data has been gathered), so the write process wouldn't interrupt the game.

**Comment by Dove-Bren** [comment]
Agree. This would be pretty cool.

I'll get working on this right now.

**Comment by Dove-Bren** [comment]
Done.
Backups are taken at regular intervals once the game has started. You can also take a manual backup. 
Games can be restored from backups.
Backups are generated for running and deathmatch games when the plugin is being disabled -- for those nasty heap and stack crashes that still produce an onDisable event.
