### ISSUE TITLE
What to do with Droppers, Dispensers, Etc

### ISSUE THREAD

**Issue by mattysweeps** [nmtminecraft/SpongeSurvivalGames#13]
I remember we had this problem a few years ago. One of the maps had splash potions in a dispenser. Someone grabbed these potions when they shouldn't have been able to, and used them to obtain victory.

When we iterate over tile entities, it might be a good idea to remove all items from all other inventory holding blocks. Of course, the trade off is: item based traps would not work.

Thoughts?

**Comment by nmtminecraft** [comment]
I think it makes sense to clear them. Or we could turn them into chests or stone or air so even if a trap is broken you can't really tell. 

Skyler

**Comment by smarti02** [comment]
I think that turning them into stone or air might be a bit overkill, but that we should definatly empty the inventories. also, I totally did not win that time :p

**Comment by mattysweeps** [comment]
Currently, all other inventory blocks are emptied when the chests are found the first time. However, this allows the possibility of a player leaving an item in a dropper which can be used in a future game

**Comment by smarti02** [comment]
could we include all things with an inventory as a chest?

**Comment by Dove-Bren** [comment]
Line 92 of GetChestsCommand.java says:
 If it has an inventory, clear it
This is only done when we're pre-processing maps. At that point, players will not be in the world / have access to the chests.
As of right now, I don't see a problem. It would be an issue if we reuse the same map back to back -- which we could solve by running the scrape command again. 

To fix this, we might want to define a 'clear inventories' command?

**Comment by mattysweeps** [comment]
I think this is ok to close.
