### ISSUE TITLE
Command to refill chests

### ISSUE THREAD

**Issue by mattysweeps** [nmtminecraft/SpongeSurvivalGames#7]
I was thinking about this this morning.
Most hunger games servers have the ability to refill chests, to keep the game going.

We could make a command which does this manually.

However, that means we should store the location of all the chests....which I apologize for, since I specifically stated how we didn't need to do that.

For extra fluff, we could make a config for a set amount of time before the chests refill (like, 30-45 minutes). That way the players will know when it's about to happen.

Or, if we would rather keep games alive by using sponsors, then we can avoid doing this.

Let me know your thoughts

**Comment by smarti02** [comment]
Sounds like a great idea to me. The command could be especially useful for the event. Also I think we're saving the chest locations out to config anyway, so I think we're already tracking them.

**Comment by Dove-Bren** [comment]
I like the idea of a command. And the sponsor can do too to keep it alive. 

I support long term auto-fill, but for now am in favor of just a command

**Comment by Dove-Bren** [comment]
Also we have chest locations stored so it would be super easy. We actually just all the fillChest task again I believe. 

Skyler
